In [1]:
import numpy as np

## Create a numpy array of int, characters, float and find their shapes

In [2]:
intarr=np.random.randint(1,100,size=25)
print(intarr.shape,'Int array :-\n',intarr)

floatarr=np.random.rand(3,4)
print(floatarr.shape,'\nFloat array :-\n',floatarr)

chararray=np.chararray((2,6))
chararray[0:][0:1] = 'A'
chararray[0:][1:] = 'Z'
print(chararray.shape,'\nChar array :-\n',chararray)

(25,) Int array :-
 [72  4 80 57 43 48 82 34 80 67 23 22  6 26 19 86 65 99  6 44 91 11 99 99
 41]
(3, 4) 
Float array :-
 [[0.65052508 0.64065417 0.13401065 0.54429694]
 [0.03926076 0.68871796 0.60400332 0.77044336]
 [0.04402385 0.99216925 0.06622029 0.60263715]]
(2, 6) 
Char array :-
 [[b'A' b'A' b'A' b'A' b'A' b'A']
 [b'Z' b'Z' b'Z' b'Z' b'Z' b'Z']]


## Create a zeros, empty, identity , eye and a full array

In [4]:
emptyarr=np.empty((1, 6))
print('empty array :-',emptyarr)

identityarr=np.identity(3)
print('\nIdentity array :-\n',identityarr)

zerosarr=np.zeros((3,3))
print('\nZeros array :-\n',zerosarr)

eyesarr=np.eye(4,4,k=-1)
print('\nEye array :-\n',eyesarr)

fullarr=np.full([4,3],fill_value=5)
print('\nFull array :-\n',fullarr)

empty array :- [[0. 0. 0. 0. 0. 0.]]

Identity array :-
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Zeros array :-
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Eye array :-
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Full array :-
 [[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


## Declare an array having the datatype of object, is it possible?

In [5]:
faizan=np.array(['Faizan',20.9,'Fast',5,'Semester'], dtype=object)
faizan

array(['Faizan', 20.9, 'Fast', 5, 'Semester'], dtype=object)

## Create an array having 5 equally spaced numbers ranging from 5 to 15

In [7]:
equal_space=np.linspace(5,16,5)
equal_space

array([ 5.  ,  7.75, 10.5 , 13.25, 16.  ])

## Create a numpy array ranging from 1 to 100.

In [9]:
onetohundred=np.arange(1,101)
onetohundred

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

## Reshape the above array into (100,15). Is it possible?

In [10]:
print('100,15 of above array is not possible however 20,5 and such that 5,20 is possible.')

100,15 of above array is not possible however 20,5 and such that 5,20 is possible.


## Reshape the array into (100,10).

In [13]:
hundtoten=np.arange(1,2001,2)
hundtoten=hundtoten.reshape(100,10)
hundtoten

array([[   1,    3,    5,    7,    9,   11,   13,   15,   17,   19],
       [  21,   23,   25,   27,   29,   31,   33,   35,   37,   39],
       [  41,   43,   45,   47,   49,   51,   53,   55,   57,   59],
       [  61,   63,   65,   67,   69,   71,   73,   75,   77,   79],
       [  81,   83,   85,   87,   89,   91,   93,   95,   97,   99],
       [ 101,  103,  105,  107,  109,  111,  113,  115,  117,  119],
       [ 121,  123,  125,  127,  129,  131,  133,  135,  137,  139],
       [ 141,  143,  145,  147,  149,  151,  153,  155,  157,  159],
       [ 161,  163,  165,  167,  169,  171,  173,  175,  177,  179],
       [ 181,  183,  185,  187,  189,  191,  193,  195,  197,  199],
       [ 201,  203,  205,  207,  209,  211,  213,  215,  217,  219],
       [ 221,  223,  225,  227,  229,  231,  233,  235,  237,  239],
       [ 241,  243,  245,  247,  249,  251,  253,  255,  257,  259],
       [ 261,  263,  265,  267,  269,  271,  273,  275,  277,  279],
       [ 281,  283,  285,  287,  2

## Flatten and ravel the reshaped array. What is the difference?

In [17]:
print('Flatten : If you modify modify any value of this array value of the original array is not affected')
print('Ravel : If you modify the array you would notice that the value of the original array also changes.')

Flatten : If you modify modify any value of this array value of the original array is not affected
Ravel : If you modify the array you would notice that the value of the original array also changes.


## Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis

In [55]:
a=np.array([[1,2,3],[4,5,6],[ 7,8,9]])
print(a)

b=np.sum(a,axis=0)
print('\nsum of above array along 0 axis :-\n',b)

c=np.sum(a,axis=1)
print('sum of above array along 1 axis :-\n',c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum of above array along 0 axis :-
 [12 15 18]
sum of above array along 1 axis :-
 [ 6 15 24]


## Find the number of bytes used by your array

In [34]:
array = np.array([1,3,5])
 
# Total bytes consumed by the elements  of the array
print('\n Bytes in 32:',array.nbytes)
################################################

array = np.array([1,3,5], dtype=np.float16)
# Total bytes consumed by the elements of the array
print('\n Bytes in 16 :',array.nbytes)

################################################

array = np.array([1,3,5], dtype=np.float64)
# Total bytes consumed by the elements of the array
print('\n Bytes in 64 :',array.nbytes)



 Bytes in 32: 12

 Bytes in 16 : 6

 Bytes in 64 : 24


## Find the maximum and minimum values in a 1D array.

In [35]:
a=np.random.randint(1,100,size=25)
print('max :',a.max(),'\nmin :',a.min())

max : 94 
min : 3


## Find the maximum and minimum values in 2D array

In [65]:
a=np.random.randint(1,100,size=(4,7))
print(a)
print('\nmax along columns:',np.amax(a,axis=0),'\nmin along columns:',np.amin(a,axis=0))
print('\nmax along rows:',np.amax(a,axis=1),'\nmin along rows:',np.amin(a,axis=1))

[[54 61 38 58 35 50 65]
 [85 94 23 93 69 16 34]
 [ 8 30 83 56 52 46 91]
 [ 6 68 74 60 10 33 77]]

max along columns: [85 94 83 93 69 50 91] 
min along columns: [ 6 30 23 56 10 16 34]

max along rows: [65 94 91 77] 
min along rows: [35 16  8  6]


## Sort an array

In [54]:
a=np.random.randint(1,100,size=(4,4))
print(a)
b=a
c=a
b.sort(1)
print('\n2d array sort along row:-\n',b)

c.sort(0)
print('\n2d array sort along column:-\n',c)

[[39 29 48 11]
 [66 37 78 91]
 [72 10 18 12]
 [65 34 33 53]]

2d array sort along row:-
 [[11 29 39 48]
 [37 66 78 91]
 [10 12 18 72]
 [33 34 53 65]]

2d array sort along column:-
 [[10 12 18 48]
 [11 29 39 65]
 [33 34 53 72]
 [37 66 78 91]]


## Is * and mul the same as dot product for numpy arrays and matrices? Check.

In [73]:
a=np.random.randint(1,10,size=(3,3))
b=np.random.randint(1,10,size=(3,3))
print(a,'\n\n',b)
c=a*b
print('\nMultiply :-\n',c)
d=np.dot(a, b)
print('\nMultiply :-\n',d)
print('np.dot and * multiplication is different np.dot is matrix multiplication while in * corresponding enteries are multiplied')

[[9 5 1]
 [4 9 8]
 [9 4 3]] 

 [[1 7 7]
 [6 7 3]
 [9 4 8]]

Multiply :-
 [[ 9 35  7]
 [24 63 24]
 [81 16 24]]

Multiply :-
 [[ 48 102  86]
 [130 123 119]
 [ 60 103  99]]
np.dot and * multiplication is different np.dot is matrix multiplication while in * corresponding enteries are multiplied


## Take the square root and norm of an array

In [83]:
a=[1,4,25,9,16,36,81,49,144]
b=np.sqrt(a)
print(b)
c=np.linalg.norm(a)
c

[ 1.  2.  5.  3.  4.  6.  9.  7.  0. 12.  0.]


178.80995498014084

## Find the std, non-zero, zero values and mean of an array

In [88]:
a=np.array([1,0,25,9,16,36,0,49,0])
print('STD :',np.std(a))
print('Mean :',np.mean(a))
print('Zeros :',a[a==0])
print('Non-zeros :',a[a!=0])

STD : 17.012704040376182
Mean : 15.11111111111111
Zeros : [0 0 0]
Non-zeros : [ 1 25  9 16 36 49]


## Convert some angles to radians and vice versa

In [92]:
angles1=np.random.uniform(0,361,12)
print('angles :',angles)
rad=np.radians(angles)
angles2=np.degrees(rad)
print('\nradians :',rad)
print('\ndegrees :',angles2)

angles : [330.22844196  87.02822993 230.52536535  21.70347626 100.40385817
  74.64145521 172.71560637 317.28448758  68.23163215 319.53809874
 173.98735669  86.63885816]

radians : [5.7635736  1.51892915 4.02342663 0.37879712 1.75237791 1.30273915
 3.014456   5.53765897 1.19086664 5.57699191 3.03665223 1.51213334]

degrees : [330.22844196  87.02822993 230.52536535  21.70347626 100.40385817
  74.64145521 172.71560637 317.28448758  68.23163215 319.53809874
 173.98735669  86.63885816]


## Save and load some of your arrays

In [94]:
arr=np.random.randint(1,10,size=10)
print(arr)
np.save('numpy_arr',arr)

[5 5 9 6 7 7 9 9 6 7]


In [95]:
np.load('numpy_arr.npy')

array([5, 5, 9, 6, 7, 7, 9, 9, 6, 7])

## Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn  from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal

In [111]:
arr=np.random.normal(21,4.5,[3,3,12,3])
arr

array([[[[18.02045352, 11.44961565, 20.12981983],
         [24.59918595, 16.81471839, 26.85932635],
         [19.67700877, 18.48450538, 21.14273221],
         [22.04427159, 19.22831712, 22.25882977],
         [28.30634948, 13.8407591 , 26.59220114],
         [23.34973426, 24.65067954, 17.52389096],
         [26.58511057, 29.96509671, 17.76080114],
         [20.66708231, 23.63614892, 21.54836732],
         [24.57566792, 19.31469885, 23.47989557],
         [21.8639483 , 13.70416343, 13.81814281],
         [17.45100941, 25.76241028, 14.33868012],
         [19.550893  , 18.86648268, 18.50462242]],

        [[20.33739665, 24.3572525 , 21.08337399],
         [25.69391426, 24.69699048, 17.97786484],
         [18.74441304, 18.38181871, 21.80615362],
         [10.45020934, 20.04244427, 19.91183062],
         [14.79927564, 19.95106455, 17.76242436],
         [24.60247949, 15.79984356, 20.41105031],
         [15.90620035, 19.6590153 , 22.46415607],
         [19.76058278, 26.65217481, 24.73779619]

In [112]:
print('Mean : ',np.mean(arr))
print('Std : ',np.std(arr))
print('Variance : ',np.var(arr))
print('Max : ',np.max(arr))
print('Min : ',np.min(arr))

Mean :  20.976285450447673
Std :  4.66973905292056
Variance :  21.806462822371408
Max :  34.759475916720774
Min :  5.02234578593186


# Lab 10_completed