In [1]:
# pip install numpy
import numpy as np

# Task1-i Making random 1X2 vector

In [2]:
import numpy as np
import pandas as pd
import math

In [3]:
v1=np.random.randint(1,9,size=(1,2))
v1

array([[7, 3]])

# Task1-ii making orthogonal vector

In [4]:
v2=np.flip(v1)
v2=np.array([-v2[0][0],v2[0][1]])
v2

array([-3,  7])

In [5]:
v1

array([[7, 3]])

# Task1-iii making projections on each other

In [6]:
tmp=math.sqrt(np.dot(v1,v1.T))
proj2=(((np.dot(v1,v2))/tmp))*v1
print("Projection of v2 on v1 : ",proj2)

tmp2=math.sqrt(np.dot(v2,v2.T))
proj1=(((np.dot(v1,v2))/tmp2))*v2
print("Projection of v1 on v2 : ",proj1)

Projection of v2 on v1 :  [[0. 0.]]
Projection of v1 on v2 :  [-0.  0.]


# Task1-iv Finding initial vectors from projection

In [7]:
print("We cannot find initial vectors from projections beacuse all enteries are zero now and their previous enteries has been lost")

We cannot find initial vectors from projections beacuse all enteries are zero now and their previous enteries has been lost


# Task1-v Findi eigenvalues and eigenvectors of iris data set

In [8]:
df=pd.read_csv(f'iris.csv')
df.drop('variety' ,inplace=True, axis=1)

In [9]:
df

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [10]:
tv=df[['sepal.length', 'sepal.width','petal.length','petal.width']].to_numpy()
tv

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
tv=np.asmatrix(tv)
tv=tv *tv.T
tv.shape

(150, 150)

In [12]:
tv.shape

(150, 150)

In [13]:
eigenvalues,eigenvectors = np.linalg.eig(tv)
print("Eigen vectors :",eigenvectors,'\n Eigen values',eigenvalues)

Eigen vectors : [[ 6.16168450e-02+0.j -1.29611444e-01+0.j -2.13859674e-03+0.j ...
  -1.11101160e-01+0.j -1.00105252e-01+0.j -1.58980246e-15+0.j]
 [ 5.80709402e-02+0.j -1.11019776e-01+0.j -7.06723871e-02+0.j ...
   9.29931089e-03+0.j -1.44012339e-04+0.j  1.63822270e-16+0.j]
 [ 5.67630474e-02+0.j -1.17966465e-01+0.j -4.34254909e-03+0.j ...
   7.35620623e-03+0.j  1.26187577e-02+0.j  3.78091651e-17+0.j]
 ...
 [ 9.40593040e-02+0.j  4.98296974e-02+0.j  4.14400144e-02+0.j ...
  -3.85583612e-02+0.j -7.51433097e-02+0.j -8.09621642e-16+0.j]
 [ 9.48896096e-02+0.j  5.61012256e-02+0.j  2.12978214e-01+0.j ...
   1.14486850e-01+0.j  7.11128093e-02+0.j  1.20114894e-15+0.j]
 [ 8.84783560e-02+0.j  5.15697045e-02+0.j  9.57528475e-02+0.j ...
   4.69514767e-03+0.j -7.81622642e-02+0.j -1.66468716e-16+0.j]] 
 Eigen values [ 9.20830507e+03+0.00000000e+00j  3.15454317e+02+0.00000000e+00j
  1.19780429e+01+0.00000000e+00j  3.55257020e+00+0.00000000e+00j
  3.66533557e-13+9.12456856e-14j  3.66533557e-13-9.12456856

# Task2-i Changing the Iris data to zero-centered data

In [14]:
df

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [15]:
mean= np.mean(df,axis=0) # takes mean across examples(along rows)
mean

sepal.length    5.843333
sepal.width     3.057333
petal.length    3.758000
petal.width     1.199333
dtype: float64

In [16]:
zero_centered=df-df.mean()
print(" Zero centered of Iris ")
zero_centered

 Zero centered of Iris 


sepal.length  sepal.width  petal.length  petal.width
0       -0.743333     0.442667        -2.358    -0.999333
1       -0.943333    -0.057333        -2.358    -0.999333
2       -1.143333     0.142667        -2.458    -0.999333
3       -1.243333     0.042667        -2.258    -0.999333
4       -0.843333     0.542667        -2.358    -0.999333
..            ...          ...           ...          ...
145      0.856667    -0.057333         1.442     1.100667
146      0.456667    -0.557333         1.242     0.700667
147      0.656667    -0.057333         1.442     0.800667
148      0.356667     0.342667         1.642     1.100667
149      0.056667    -0.057333         1.342     0.600667

[150 rows x 4 columns]

# # Task2-ii Changing the ECG data to zero-centered data

In [17]:
df2=pd.read_csv(f'ECG200_TRAIN.csv',delimiter='  ')
df2

<ipython-input-17-64b330830981>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df2=pd.read_csv(f'ECG200_TRAIN.csv',delimiter='  ')


-1.0000000e+00   5.0205548e-01   5.4216265e-01   7.2238348e-01  \
0              1.0        0.147647        0.804668        0.367771   
1             -1.0        0.316646        0.243199        0.370471   
2             -1.0        1.168874        2.075901        1.760141   
3              1.0        0.648658        0.752026        2.636231   
4              1.0        0.404733        1.280859        2.515148   
..             ...             ...             ...             ...   
94             1.0        0.581277        0.876188        1.042767   
95            -1.0        2.689017        2.708703        2.008381   
96            -1.0        0.197677        0.455417        0.973110   
97             1.0        0.179500        1.038409        1.946421   
98             1.0        0.073124        0.776054        2.181336   

     1.4288852e+00   2.1365158e+00   2.2811490e+00   1.9362737e+00  \
0         0.243894        0.026614       -0.274402        0.096731   
1         1.063738        1.678187        1.759558        1.697717   
2         1.606446        1.949046        1.302842        0.459332   
3         3.455716        2.118157        0.520620       -0.188627   
4         1.299519        1.453432        0.474275       -1.396562   
..             ...             ...             ...             ...   
94        1.796120        2.541399        2.246653        1.500387   
95        2.235800        1.516982        0.029916       -0.561346   
96        1.935956        2.259463        1.741341        1.158296   
97        2.705141        1.670706       -0.101167       -1.578876   
98        3.440325        2.168475        0.497315       -0.924284   

     1.4688900e+00   1.0088451e+00  ...   9.3104294e-01   6.1029836e-01  \
0        -0.747731       -1.609777  ...       -0.533503       -0.400228   
1         1.612159        1.168188  ...        0.764229        0.610621   
2         0.516412        0.852180  ...        0.419006        0.723888   
3         0.780818        0.933775  ...       -0.097869       -0.136787   
4        -0.647081        0.431945  ...        0.376469        0.277811   
..             ...             ...  ...             ...             ...   
94        1.031521        0.382672  ...        1.002770        0.907869   
95       -0.793702       -0.979371  ...       -0.136610       -0.072176   
96        0.418241       -0.071605  ...        0.482452        0.325569   
97       -0.750906        0.175310  ...        0.324323        0.330489   
98       -1.499227       -0.679328  ...       -0.058935       -0.130638   

     6.3889427e-01   6.8467857e-01   5.8323764e-01   6.4052167e-01  \
0         0.176084        1.111768        2.438428        2.734889   
1         0.552900        0.566786        0.604002        0.777068   
2         1.323947        2.136488        1.746597        1.470220   
3        -0.340237       -0.089441       -0.080297       -0.192584   
4         0.225676        0.159091        0.408354        0.540015   
..             ...             ...             ...             ...   
94        0.916457        0.923975        0.767357        0.656223   
95       -0.082738       -0.138468       -0.120396       -0.089411   
96        0.247991        0.184127        0.050358        0.241988   
97        0.111953        0.448948        0.567132        0.136757   
98       -0.347235       -0.177933       -0.060332       -0.347634   

     7.0858515e-01   7.0501088e-01   7.1381545e-01   4.3376464e-01  
0         1.736054        0.036857       -1.265074       -0.208024  
1         0.812345        0.748848        0.818042        0.539347  
2         1.893512        1.256949        0.800407        0.731540  
3        -0.304704       -0.454556        0.314590        0.582190  
4        -0.027791        0.203476        0.346964        0.339185  
..             ...             ...             ...             ...  
94        0.762357        0.501373       -0.333336       -0.524546  
95       -0.243141       -0.

In [18]:
df2.drop('-1.0000000e+00',inplace=True,axis=1)
df2

5.0205548e-01   5.4216265e-01   7.2238348e-01   1.4288852e+00  \
0         0.147647        0.804668        0.367771        0.243894   
1         0.316646        0.243199        0.370471        1.063738   
2         1.168874        2.075901        1.760141        1.606446   
3         0.648658        0.752026        2.636231        3.455716   
4         0.404733        1.280859        2.515148        1.299519   
..             ...             ...             ...             ...   
94        0.581277        0.876188        1.042767        1.796120   
95        2.689017        2.708703        2.008381        2.235800   
96        0.197677        0.455417        0.973110        1.935956   
97        0.179500        1.038409        1.946421        2.705141   
98        0.073124        0.776054        2.181336        3.440325   

     2.1365158e+00   2.2811490e+00   1.9362737e+00   1.4688900e+00  \
0         0.026614       -0.274402        0.096731       -0.747731   
1         1.678187        1.759558        1.697717        1.612159   
2         1.949046        1.302842        0.459332        0.516412   
3         2.118157        0.520620       -0.188627        0.780818   
4         1.453432        0.474275       -1.396562       -0.647081   
..             ...             ...             ...             ...   
94        2.541399        2.246653        1.500387        1.031521   
95        1.516982        0.029916       -0.561346       -0.793702   
96        2.259463        1.741341        1.158296        0.418241   
97        1.670706       -0.101167       -1.578876       -0.750906   
98        2.168475        0.497315       -0.924284       -1.499227   

     1.0088451e+00   3.8028224e-01  ...   9.3104294e-01   6.1029836e-01  \
0        -1.609777       -1.179593  ...       -0.533503       -0.400228   
1         1.168188        0.499957  ...        0.764229        0.610621   
2         0.852180        0.989227  ...        0.419006        0.723888   
3         0.933775        0.701402  ...       -0.097869       -0.136787   
4         0.431945        0.132445  ...        0.376469        0.277811   
..             ...             ...  ...             ...             ...   
94        0.382672       -0.197561  ...        1.002770        0.907869   
95       -0.979371       -1.288162  ...       -0.136610       -0.072176   
96       -0.071605       -0.241250  ...        0.482452        0.325569   
97        0.175310        0.064901  ...        0.324323        0.330489   
98       -0.679328       -0.549892  ...       -0.058935       -0.130638   

     6.3889427e-01   6.8467857e-01   5.8323764e-01   6.4052167e-01  \
0         0.176084        1.111768        2.438428        2.734889   
1         0.552900        0.566786        0.604002        0.777068   
2         1.323947        2.136488        1.746597        1.470220   
3        -0.340237       -0.089441       -0.080297       -0.192584   
4         0.225676        0.159091        0.408354        0.540015   
..             ...             ...             ...             ...   
94        0.916457        0.923975        0.767357        0.656223   
95       -0.082738       -0.138468       -0.120396       -0.089411   
96        0.247991        0.184127        0.050358        0.241988   
97        0.111953        0.448948        0.567132        0.136757   
98       -0.347235       -0.177933       -0.060332       -0.347634   

     7.0858515e-01   7.0501088e-01   7.1381545e-01   4.3376464e-01  
0         1.736054        0.036857       -1.265074       -0.208024  
1         0.812345        0.748848        0.818042        0.539347  
2         1.893512        1.256949        0.800407        0.731540  
3        -0.304704       -0.454556        0.314590        0.582190  
4        -0.027791        0.203476        0.346964        0.339185  
..             ...             ...             ...             ...  
94        0.762357        0.501373       -0.333336       -0.524546  
95       -0.243141       -0.1

In [19]:
zero_centered2=df2-df2.mean()
print(" Zero centered of ECG ")
zero_centered2

 Zero centered of ECG 


5.0205548e-01   5.4216265e-01   7.2238348e-01   1.4288852e+00  \
0        -0.562875       -0.626371       -1.684678       -1.889607   
1        -0.393876       -1.187841       -1.681978       -1.069763   
2         0.458352        0.644861       -0.292309       -0.527055   
3        -0.061865       -0.679014        0.583781        1.322214   
4        -0.305790       -0.150181        0.462698       -0.833982   
..             ...             ...             ...             ...   
94       -0.129245       -0.554852       -1.009683       -0.337381   
95        1.978495        1.277664       -0.044068        0.102299   
96       -0.512845       -0.975623       -1.079340       -0.197545   
97       -0.531022       -0.392631       -0.106029        0.571640   
98       -0.637398       -0.654986        0.128886        1.306824   

     2.1365158e+00   2.2811490e+00   1.9362737e+00   1.4688900e+00  \
0        -1.519094       -1.021311       -0.169213       -1.069893   
1         0.132479        1.012649        1.431773        1.289997   
2         0.403337        0.555934        0.193388        0.194250   
3         0.572449       -0.226288       -0.454570        0.458656   
4        -0.092276       -0.272633       -1.662506       -0.969243   
..             ...             ...             ...             ...   
94        0.995691        1.499744        1.234443        0.709358   
95       -0.028727       -0.716992       -0.827290       -1.115864   
96        0.713755        0.994432        0.892352        0.096079   
97        0.124998       -0.848075       -1.844820       -1.073068   
98        0.622767       -0.249593       -1.190228       -1.821389   

     1.0088451e+00   3.8028224e-01  ...   9.3104294e-01   6.1029836e-01  \
0        -1.976327       -1.388649  ...       -0.716434       -0.570110   
1         0.801638        0.290901  ...        0.581298        0.440740   
2         0.485630        0.780171  ...        0.236076        0.554006   
3         0.567225        0.492346  ...       -0.280800       -0.306668   
4         0.065395       -0.076611  ...        0.193538        0.107930   
..             ...             ...  ...             ...             ...   
94        0.016122       -0.406618  ...        0.819840        0.737987   
95       -1.345921       -1.497218  ...       -0.319541       -0.242057   
96       -0.438155       -0.450306  ...        0.299522        0.155688   
97       -0.191240       -0.144155  ...        0.141393        0.160607   
98       -1.045878       -0.758948  ...       -0.241866       -0.300519   

     6.3889427e-01   6.8467857e-01   5.8323764e-01   6.4052167e-01  \
0        -0.024641        0.829306        2.027689        2.277342   
1         0.352175        0.284324        0.193263        0.319521   
2         1.123222        1.854026        1.335857        1.012674   
3        -0.540962       -0.371903       -0.491036       -0.650131   
4         0.024951       -0.123371       -0.002385        0.082468   
..             ...             ...             ...             ...   
94        0.715732        0.641513        0.356618        0.198677   
95       -0.283463       -0.420930       -0.531135       -0.546958   
96        0.047266       -0.098335       -0.360381       -0.215558   
97       -0.088772        0.166486        0.156393       -0.320789   
98       -0.547960       -0.460395       -0.471071       -0.805180   

     7.0858515e-01   7.0501088e-01   7.1381545e-01   4.3376464e-01  
0         1.349421       -0.241743       -1.442540       -0.380272  
1         0.425713        0.470248        0.640576        0.367099  
2         1.506879        0.978349        0.622941        0.559292  
3        -0.691337       -0.733156        0.137124        0.409941  
4        -0.414424       -0.075124        0.169498        0.166937  
..             ...             ...             ...             ...  
94        0.375724        0.222773       -0.510802       -0.696794  
95       -0.629773       -0.3

# Completed task